//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Repository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PrediccionesSDFEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PrediccionesSDFEntities1 object using the connection string found in the 'PrediccionesSDFEntities1' section of the application configuration file.
        /// </summary>
        public PrediccionesSDFEntities1() : base("name=PrediccionesSDFEntities1", "PrediccionesSDFEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrediccionesSDFEntities1 object.
        /// </summary>
        public PrediccionesSDFEntities1(string connectionString) : base(connectionString, "PrediccionesSDFEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrediccionesSDFEntities1 object.
        /// </summary>
        public PrediccionesSDFEntities1(EntityConnection connection) : base(connection, "PrediccionesSDFEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
